(!colophon dont-credit-tex2page)
(!definitely-latex)
(!using-chapters)
(!using-chapters)
(!toc-page 2)
(!using-chapters)
(!toc-entry 0 "A" 3 "node_chap_A" "Standard-conformant mode")
(!using-chapters)
(!toc-entry 0 "B" 4 "node_chap_B" "Optional case insensitivity")
(!index 2 4)
(!index 4 4)
(!using-chapters)
(!toc-entry 0 "C" 5 "node_chap_C" "Use of square brackets")
(!using-chapters)
(!toc-entry 0 "D" 6 "node_chap_D" "Scripts")
(!index 6 6)
(!index 8 6)
(!toc-entry 1 "D.1" 6 "node_sec_D.1" "Script interpreter")
(!index 10 6)
(!toc-entry 1 "D.2" 6 "node_sec_D.2" "Syntax")
(!index 12 6)
(!toc-entry 2 "D.2.1" 6 "node_sec_D.2.1" "Script header")
(!index 14 6)
(!toc-entry 2 "D.2.2" 6 "node_sec_D.2.2" "Example")
(!toc-entry 1 "D.3" 6 "node_sec_D.3" "Platform considerations")
(!toc-entry 2 "D.3.1" 6 "node_sec_D.3.1" "Apple Mac OS X")
(!toc-entry 2 "D.3.2" 6 "node_sec_D.3.2" "Unix")
(!toc-entry 2 "D.3.3" 6 "node_sec_D.3.3" "Microsoft Windows")
(!toc-entry 2 "D.3.4" 6 "node_sec_D.3.4" "Selecting an implementation")
(!using-chapters)
(!toc-entry 0 "E" 7 "node_chap_E" "Source code representation")
(!using-chapters)
(!toc-entry 0 "F" 8 "node_chap_F" "Use of library versions")
(!using-chapters)
(!toc-entry 0 "G" 9 "node_chap_G" "Unique library names")
(!using-chapters)
(!last-page-number 10)
(!last-modification-time 1190820146)
(!head-line "")
(!foot-line "\\folio")
(!preferred-title "Revised^6 Report on the Algorithmic Language Scheme - Rationale -")
